version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: tito
      POSTGRES_PASSWORD: one_2_three_4_five
      POSTGRES_DB: study_planner
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
